# Generated by Django 4.0.4 on 2022-08-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temoignage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temoignage',
            name='statut',
            field=models.BooleanField(default=False, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='temoignage',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='Temoignage'),
        ),
    ]
