# Generated by Django 4.0.4 on 2022-08-21 08:56

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetCategorie',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Create date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('nom_categorie', models.CharField(max_length=100, verbose_name='Libelle')),
                ('slug', models.SlugField(max_length=200, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Categorie des Projets',
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('client', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('surface', models.CharField(blank=True, max_length=100, null=True)),
                ('annee', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('architect', models.CharField(blank=True, max_length=100, null=True)),
                ('description', django_quill.fields.QuillField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Projets_images')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='Projets_images')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='Projets_images')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='Projets_images')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='Projets_images')),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Create date')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_cProjetategorie', to='projet.projetcategorie')),
            ],
            options={
                'verbose_name': 'Projet',
                'ordering': ['-created'],
            },
        ),
    ]
