# Generated by Django 4.0.4 on 2022-08-21 10:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projet',
            options={'ordering': ['-updated'], 'verbose_name': 'Projet'},
        ),
        migrations.RemoveField(
            model_name='projet',
            name='id',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='slug',
        ),
        migrations.AddField(
            model_name='projet',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='projet',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Update date'),
        ),
    ]
