# Generated by Django 4.0.4 on 2022-08-21 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0002_alter_projet_options_remove_projet_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projet',
            old_name='status',
            new_name='statut',
        ),
    ]
