# Generated by Django 4.0.4 on 2022-08-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='statut',
            field=models.BooleanField(default=False, verbose_name='Statut'),
        ),
    ]
