# Generated by Django 4.0.4 on 2022-08-21 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_team_statut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='specialite',
            new_name='fonction',
        ),
    ]
