# Generated by Django 4.1 on 2022-08-08 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='statut',
            field=models.BooleanField(default=False, verbose_name='Statut'),
        ),
    ]
