# Generated by Django 4.0.4 on 2022-08-21 09:27

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='detail',
            field=django_quill.fields.QuillField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services'),
        ),
        migrations.AlterField(
            model_name='service',
            name='statut',
            field=models.BooleanField(default=False),
        ),
    ]
