# Generated by Django 4.0.4 on 2022-08-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0007_alter_customuser_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='contry',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='linkdin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='session_token',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='specialite',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='twitter',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
